global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'backend-current'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'backend:3001'
          - 'backend_blue:3001'
          - 'backend_green:3001'
          - 'dorami-backend-prod:3001'
          - 'dorami-backend-blue:3001'
          - 'dorami-backend-green:3001'

  - job_name: 'frontend-current'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'frontend:3000'
          - 'frontend_blue:3000'
          - 'frontend_green:3000'
          - 'dorami-frontend-prod:3000'
          - 'dorami-frontend-blue:3000'
          - 'dorami-frontend-green:3000'
